#!/bin/bash

PROG=${0##*/}
# Restore the environment so that we have a sane PATH and can find, e.g.,
# tpm2-tools.
# shellcheck disable=SC1090 disable=SC1091
. ./env

set -euo pipefail
shopt -s extglob

TMPDIR=$PWD
[[ -n ${TPM2_POLICY_SESSION:-} ]]	\
|| die "TPM2_POLICY_SESSION is not set"
[[ ${TPM2_POLICY_SESSION} != */* ||
   ${TPM2_POLICY_SESSION} = ${PWD}/* ]]	\
|| die "TPM2_POLICY_SESSION does not exist"
[[ -s ${TPM2_POLICY_SESSION} ]]		\
|| die "TPM2_POLICY_SESSION does not exist"

# shellcheck disable=SC2209
function usage {
	((${1:-1} > 0)) && exec 1>&2
	pager=cat
	if [[ -t 0 && -t 1 && -t 2 ]]; then
		if [[ -z ${PAGER:-} ]] && type less >/dev/null 2>&1; then
			pager=less
		elif [[ -z ${PAGER:-} ]] && type more >/dev/null 2>&1; then
			pager=more
		elif [[ -n ${PAGER:-} ]]; then
			pager=$PAGER
		fi
	fi
        $pager <<EOF
Usage: $PROG [options]

  {$PROG} is a wrapper around {tpm2 flushcontext}.

  See {${BASEDIR}/sbin/tpm2-policy}.

  Options:

   -h | --help				This help message.
   -x | --trace				Trace this script.
   -t | --transient-object
   -l | --loaded-session
   -s | --saved-session
EOF
	exit "${1:-1}"
}

# shellcheck disable=SC1090 disable=SC1091
. "$BASEDIR/functions.sh"

# shellcheck disable=SC2034
declare -A lopts=(
	[help]=''
	[trace]=''
	[transient-object]=:
	[loaded-session]=:
	[saved-session]=:
)

declare -a args=(--policy "$TPM2_POLICY" --session "$TPM2_POLICY_SESSION")

while getopts_long lopts +:hxlst opt "$@"; do
# opt is set in getopts_long
# shellcheck disable=SC2154
case "$opt" in
h|help)		usage 0;;
x|trace)	set -vx;;
t|transient-object|l|loaded-session|s|saved-session)
		args+=(-"${OPTOPT}$opt" "$OPTARG");;
*)		usage;;
esac
done
shift $((OPTIND - 1))

# Finally:
tpm2_flushcontext "${args[@]}" "$@"
