#!/bin/bash

PROG=${0##*/}
# shellcheck disable=SC1090 disable=SC1091
. ./env

set -euo pipefail
shopt -s extglob

TMPDIR=$PWD
[[ -n ${TPM2_POLICY_SESSION:-} ]]	\
|| die "TPM2_POLICY_SESSION is not set"
[[ ${TPM2_POLICY_SESSION} != */* ||
   ${TPM2_POLICY_SESSION} = ${PWD}/* ]]	\
|| die "TPM2_POLICY_SESSION does not exist"
[[ -s ${TPM2_POLICY_SESSION} ]]		\
|| die "TPM2_POLICY_SESSION does not exist"

# shellcheck disable=SC2209
function usage {
	((${1:-1} > 0)) && exec 1>&2
	pager=cat
	if [[ -t 0 && -t 1 && -t 2 ]]; then
		if [[ -z ${PAGER:-} ]] && type less >/dev/null 2>&1; then
			pager=less
		elif [[ -z ${PAGER:-} ]] && type more >/dev/null 2>&1; then
			pager=more
		elif [[ -n ${PAGER:-} ]]; then
			pager=$PAGER
		fi
	fi
        $pager <<EOF
Usage: $PROG [options]

  {$PROG} is a wrapper around {tpm2 verifysignature}.

  See {${BASEDIR}/sbin/tpm2-policy}.

  Options:

   -h | --help			This help message.
   -x | --trace			Trace this script.

  Options from {tpm2 verifysignature}:

   -c | --key-context FILE
   -t | --ticket FILE
   -g | --hash-algorithm ALGORITHM
   -m | --message FILE
   -d | --digest FILE
   -s | --signature FILE
   -f | --scheme SCHEME

  Input and output files are limited to files in the current directory.
EOF
	exit "${1:-1}"
}

# shellcheck disable=SC1090 disable=SC1091
. "$BASEDIR/functions.sh"

# shellcheck disable=SC2034
declare -A lopts=(
	[hash-algorithm]=:
	[scheme]=:
	[message]=:
	[signature]=:
	[key-context]=:
	[ticket]=:
)

declare -a args=()

while getopts_long lopts +:hxc:t:g:m:d:s:f: opt "$@"; do
# opt is set in getopts_long
# shellcheck disable=SC2154
case "$opt" in
h|help)			usage 0;;
x|trace)		set -vx;;
g|hash-algorithm|f|scheme)
	args+=(-"${OPTOPT}$opt" "$OPTARG");;
c|key-context|t|ticket|m|message|s|signature)
	[[ $OPTARG = */* ]]	\
	&& die "Cannot reference input files outside the current directory"
	args+=(-"${OPTOPT}$opt" "$OPTARG");;
*)	usage;;
esac
done
shift $((OPTIND - 1))

# Finally:
tpm2_verifysignature "${args[@]}" "$@"
