#!/bin/bash

PROG=${0##*/}
# shellcheck disable=SC1090 disable=SC1091
. ./env

set -euo pipefail
shopt -s extglob

TMPDIR=$PWD

# shellcheck disable=SC2209
function usage {
	((${1:-1} > 0)) && exec 1>&2
	pager=cat
	if [[ -t 0 && -t 1 && -t 2 ]]; then
		if [[ -z ${PAGER:-} ]] && type less >/dev/null 2>&1; then
			pager=less
		elif [[ -z ${PAGER:-} ]] && type more >/dev/null 2>&1; then
			pager=more
		elif [[ -n ${PAGER:-} ]]; then
			pager=$PAGER
		fi
	fi
        $pager <<EOF
Usage: $PROG [options] FILE

  {$PROG} reads from stdin and writes to {FILE} provided {FILE} is in the
  current directory.

  See {${BASEDIR}/sbin/tpm2-policy}.

  Options:

   --help	This message
   --hex	Decode stdin as hex to binary
EOF
	exit "${1:-1}"
}

# shellcheck disable=SC1090 disable=SC1091
. "$BASEDIR/functions.sh"

# shellcheck disable=SC2034
declare -A lopts=(
	[help]=''
	[hex]=''
)

hex=false
while getopts_long lopts +:h opt "$@"; do
# opt is set in getopts_long
# shellcheck disable=SC2154
case "$opt" in
h|help)	usage 0;;
hex)	hex=true;;
*)	usage;;
esac
done
shift $((OPTIND - 1))
(($# == 1)) || usage

[[ $1 = */* ]] && die "Cannot write files outside current directory"
[[ -s $1 ]] && die "Cannot clobber files"

# Finally:
if $hex; then
	xxd -p -r > "$1"
else
	cat > "$1"
fi
