#!/bin/bash
set -x
KEY="$1"
if [ -z "$KEY" ]; then
	KEY="/tmp/secret.bin"
fi

# add the decryption key to initrd
# the source initrd must be padded to 512 bytes or else the kernel
# won't look for additional cpio files appended after it.
dd \
	if=/root/boot/initrd.img \
	of=/tmp/initrd.img \
	bs=512 \
	conv=sync

# Append a cpio file with a single rootfs.key file that contains the
# secret to decrypt the root filesystem.
mkdir -p /tmp/initrd
cp "$KEY" /tmp/initrd/rootfs.key
( cd /tmp/initrd ; echo rootfs.key | cpio -H newc -o ) >> /tmp/initrd.img

# Load the official kernel and the modified initrd
# passing in the command line arguments to decrypt the
# encrypted disk, and then mount the real root filesystem
# by label.
kexec \
	--load /root/boot/vmlinuz \
	--initrd /tmp/initrd.img \
	--command-line "console=ttyS0 root=LABEL=cloudimg-rootfs ro cryptopts=target=rootfs,source=/dev/sda,key=/rootfs.key,luks,discard"

kexec -e
