#!/bin/bash
# Take over from /init once the system has been configured
# and the state attested.  The secret file from the remote attestation server
# will be passed on the command line

#set -x
POLICY_PCR=11
die() {
	echo >&2 "$@"
	echo "FAILED" | tpm2 pcrevent $POLICY_PCR
	exit 1
}
warn() { echo >&2 "$@" ; }

DEV="/dev/sda"
VOLUME="cryptroot"
MAPPER="/dev/mapper/$VOLUME"
KERNEL="/root/boot/vmlinuz"
INITRD="/root/boot/initrd.img"
KEXEC_EXTRA=""
URL=""

# Unpack the attestation server's response
TMPDIR=$(mktemp -d)
tar -xvf - -C "$TMPDIR" \
|| die "attestation response is not a valid tar file?"

STARTUP="$TMPDIR/startup.sh"
KEY="$TMPDIR/rootfs.key"

if [ -x "$STARTUP" ]; then
	# measure the startup script before doing anything else
	warn "$STARTUP: measuring"
	tpm2 pcrevent 14 "$STARTUP"
	warn "$STARTUP: executing"
	. "$STARTUP" || die "startup failed"
fi

tpm2_ek_session() {
	tpm2 flushcontext -t
	tpm2 flushcontext -s
	tpm2 startauthsession \
		--session "ek-session.ctx" \
		--policy-session \
	|| die "tpm2: unable to start policy session"
	tpm2 policysecret \
		--session "ek-session.ctx" \
		--object-context endorsement \
	|| die "tpm2: unable to set policysecret for endorsement hierarchy"
}
tpm2_tk_session() {
	tpm2 startauthsession \
		--session "tk-session.ctx" \
		--policy-session \
	|| die "tpm2: unable to start tk-policy session"
	tpm2 policypcr \
		--session "tk-session.ctx" \
		--policy "tk-policy.dat" \
		--pcr-list="sha256:$POLICY_PCR" \
	|| die "tpm2: unable to load policy pcr"
}

if [ -r "$TMPDIR/transport.seed" ]; then
	# attempt to load the secret wrapping key into our TPM
	# as a transient object
	tpm2 createek \
		--ek-context ek.ctx \
	|| die "tpm2: unable to create ek object"

	warn "tpm2: Importing duplicate transport key"
	tpm2_ek_session

	tpm2 import \
		--parent-context ek.ctx \
		--parent-auth "session:ek-session.ctx" \
		--key-algorithm rsa \
		--input "$TMPDIR/transport.dpriv" \
		--seed "$TMPDIR/transport.seed" \
		--public "$TMPDIR/transport.pub" \
		--private "$TMPDIR/transport.priv" \
	|| die "tpm2: unable to import duplicate transport key object"

	warn "tpm2: Loading duplicate transport key"
	tpm2_ek_session
	tpm2 load \
		--parent-context ek.ctx \
		--auth "session:ek-session.ctx" \
		--key-context "$TMPDIR/transport.ctx" \
		--public "$TMPDIR/transport.pub" \
		--private "$TMPDIR/transport.priv" \
	|| die "tpm2: unable to load duplicate transport key object"

	# attempt to decrypt the rootfs key with the transport key
	warn "tpm2: Decrypting rootfs key"
	tpm2_tk_session
	tpm2 rsadecrypt \
		--auth "session:tk-session.ctx" \
		--key-context "$TMPDIR/transport.ctx" \
		< "$TMPDIR/rootfs.enc.key" \
		> "$TMPDIR/rootfs.key" \
	|| die "tpm2: unable to decrypt the rootfs key with transport key"

	# extend PCR11 so that the policy can not be satisfied
	echo "UNLOCKED" | tpm2 pcrevent "$POLICY_PCR" \
	|| die "tmp2: unable to extend PCR$POLICY_PCR"
fi

kexec_img() {
	# add the decryption key to initrd by creating a temporary copy
	# the source initrd must be padded to 512 bytes or else the kernel
	# won't look for additional cpio files appended after it.
	TMP_INITRD="$TMPDIR/initrd.img"

	warn "$INITRD: adding secret key"

	dd \
		if="$INITRD" \
		of="$TMP_INITRD" \
		bs=512 \
		conv=sync \
	|| die "$INITRD: unable to copy to $TMPDIR"

	# todo: these are causing swtpm to timeout?
	#warn "$KERNEL: measuring"
	#tpm2 pcrevent 14 < "$KERNEL"
	#warn "$TMP_INITRD: measuring"
	#tpm2 pcrevent 14 < "$TMP_INITRD"

	if [ -r "$KEY" ]; then
		# Append a cpio file with a single rootfs.key file that contains the
		# secret to decrypt the root filesystem.
		mkdir -p "$TMPDIR/initrd"
		cp "$KEY" "$TMPDIR/initrd/rootfs.key" \
		|| die "$KEY: unable to copy secret key"

		( cd "$TMPDIR/initrd" ; echo rootfs.key | cpio -H newc -o ) >> "$TMP_INITRD" \
		|| die "$TMP_INITRD: unable to add $KEY to initrd"

		KEXEC_EXTRA="$KEXEC_EXTRA \
cryptopts=target=rootfs,source=/dev/sda,key=/rootfs.key,luks,discard \
"

	else
		warn "response did not include encrypted rootfs.key"
	fi

	# Load the official kernel and the modified initrd
	# passing in the command line arguments to decrypt the
	# encrypted disk, and then mount the real root filesystem
	# by label.
	KEXEC_CMDLINE="\
console=ttyS0 \
root=LABEL=cloudimg-rootfs \
ro \
$KEXEC_EXTRA \
"
	warn "$KERNEL: $KEXEC_CMDLINE"

	kexec \
		--load "$KERNEL" \
		--initrd "$TMP_INITRD" \
		--command-line "$KEXEC_CMDLINE" \
	|| die "$KERNEL: unable to load with kexec"

	kexec -e

	# if we end up here, we're in trouble...
	die "$KERNEL: kexec failed"
}

mount_img() {
	mkdir -p /run/cryptsetup

	warn "$DEV: unlocking with secret key"
	cryptsetup luksOpen \
		--key-file "$KEY" \
		"$DEV" \
		"$VOLUME"
}

install_img() {
	if [ -z "$URL" ]; then
		die "No disk image, no image URL to fetch. Nothing to do!"
	fi

	if [ -e "$MAPPER" ]; then
		cryptsetup luksClose "$VOLUME"
	fi

	#blockdev --setrw "$DEV"

	warn "$DEV: formatting with secret key"
	cryptsetup luksFormat \
		--pbkdf pbkdf2 \
		--batch-mode \
		--label="$VOLUME" \
		"$DEV" \
		"$KEY" \
	|| die "$DEV: luksFormat failed"

	mount_img \
	|| die "$DEV: luksOpen failed"

	warn "$MAPPER: fetching disk image"
	curl "$URL" | tee "$MAPPER" | sha256sum - | tee "$TMPDIR/url.hash" \
	|| die "$DEV: unable to fetch $URL"

	if [ -r "$TMPDIR/img.hash" ]; then
		if ! cmp "$TMPDIR/img.hash" "$TMPDIR/url.hash" ; then
			die "$URL: hash failed!"
		fi

		warn "$URL: verified $URL_HASH"
	fi

	#blockdev --rereadpt "$MAPPER"

	echo "$MAPPER: File system installed"

	mount "$MAPPER" /root \
	|| die "$MAPPER: unable to mount?"

	# stash the server configuration in the encrypted /boot
	# if it was provided in the response
	if [ -r "$TMPDIR/user-data" ]; then
		warn "cloud-init: creating user-data"
		KEXEC_EXTRA="$KEXEC_EXTRA ds=nocloud;s=file:///boot/cloud-init/"
		mkdir -p /root/boot/cloud-init
		cp "$TMPDIR/user-data" /root/boot/cloud-init \
		|| die "user-data: unable to install"

		if [ -r "$TMPDIR/meta-data" ]; then
			cp "$TMPDIR/meta-data" /root/boot/cloud-init \
			|| die "meta-data: unable to install"
		fi
	fi

	# remove our write permissions
	mount -o ro,remount /root
}


# ensure that we don't accidentally touch the root device
# this breaks fsck, which is a problem
#blockdev --setro /dev/sda

# attempt to decrypt the disk; if this fails, reinstall an image
if ! mount_img || ! mount -o ro "$MAPPER" /root ; then
	warn "-------------------------------"
	warn "Unable to unlock and mount disk"
	warn "-------------------------------"

	read -r -n 1 -t 10 -p "Press any key to stop reinstall..." response
	if [ -n "$response" ]; then
		exit 0
	fi

	warn "No init in root filesystem, reinstalling"
	install_img
else
	echo "$MAPPER: unlock and mount successful"
fi

if [ ! -e "$KERNEL" ]; then
	die "$KERNEL: No kernel present in image?"
fi

read -r -n 1 -t 3 -p "Press any key to stop autoboot..." response
if [ -n "$response" ]; then
	exit 0
fi

kexec_img

die "kexec failed and we ended up here?"
