#!/bin/bash
echo "Hello, initrd"
mkdir -p /proc /sys /tmp /dev /etc /root
mount -t proc none /proc
mount -t devtmpfs none /dev
mount -t sysfs none /sys
mount -t efivarfs none /sys/firmware/efi/efivars

echo "Hello, ttyprintk" > /dev/ttyprintk
echo "hello console" > /dev/console

export PS1='\h:\w# '
exec setsid --ctty /bin/bash </dev/console >/dev/console 2>/dev/console
