#!/bin/bash
# Reads the secret key from stdin, creates and formats the disk,
# then fetches the disk image from the command line

set -x
die() { echo >&2 "$@" ; exit 1 ; }

DEV=/dev/sda
KEY=/tmp/key.bin
VOLUME=cryptroot
MAPPER=/dev/mapper/$VOLUME

KEY="$1"
URL="$2"

if [ -z "$KEY" ]; then
	KEY="/tmp/secret.bin"
fi

if [ -z "$URL" ]; then
	URL="http://10.0.2.2:8000/focal-server-cloudimg-amd64.img"
fi


if [ -e "$MAPPER" ]; then
	cryptsetup luksClose "$VOLUME"
fi

blockdev --setrw "$DEV"

cryptsetup luksFormat \
	--pbkdf pbkdf2 \
	--batch-mode \
	--label="$VOLUME" \
	"$DEV" \
	"$KEY" \
|| die "$DEV: luksFormat failed"

cryptsetup luksOpen \
	--key-file "$KEY" \
	"$DEV" \
	"$VOLUME" \
|| die "$DEV: luksOpen failed"

curl "$URL" > "$MAPPER" \
|| die "$DEV: unable to fetch $URL"

blockdev --rereadpt "$MAPPER"

echo "$DEV: File system installed"
mount "$MAPPER" /root
