#!/bin/sh
# goes in /etc/initramfs-tools/hooks/overlay

# Ensure that overlayfs is loaded.

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules overlay
