#!/bin/bash

set -euo pipefail
shopt -s extglob

BINDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

gencert_override() {
	GENCERT_OUTPUT+="-pkinit-client"
	GENCERT_PKINIT_CLIENT=true
	GENCERT_PKINIT_KDC=false
	GENCERT_HTTPS_CLIENT=false
	GENCERT_HTTPS_SERVER=false
}

source $BINDIR/gencert
