#!/bin/bash
# Given a list of hashes, predict the eventual value of a PCR
hex2bin() { xxd -p -r ; }
bin2hex() { xxd -p ; }
sha256() { sha256sum - | cut -d' ' -f1 ; }

pcr=0000000000000000000000000000000000000000000000000000000000000000

tpm2_trial_extend() {
	initial="$1"
	newhash="$2"
	printf "%s" "$initial$newhash" | hex2bin | sha256
}

for hash in $*; do
	pcr=`tpm2_trial_extend $pcr $hash`
done

echo $pcr
