#!/bin/bash
# Safer Booting with UEFI Secure Boot and the TPM
#
# Be careful with this, it is possible to lock yourself
# out of your computer if you lose the firmware password
# and platform signing keys.
#
# For more details: https://safeboot.dev/
#
set -e -o pipefail

: ${PREFIX:=}
: ${DIR:=/etc/safeboot}

if [ -r "$PREFIX$DIR/safeboot.conf" ]; then
	. $PREFIX$DIR/safeboot.conf
fi

# Apply $PREFIX to files and use default value
CERT=$PREFIX${CERT:-$DIR/cert.pem}
KERNEL=$PREFIX${KERNEL:-/boot/vmlinuz}
INITRD=$PREFIX${INITRD:-/boot/initrd.img}
EFIDIR=$PREFIX${EFIDIR:-/boot/efi/EFI}

if [ "$KEY" == "pkcs11:" ]; then
	# KEY is a hardware token, use the yubikey engine
	KEY_ENGINE="-e pkcs11"
else
	# KEY is a normal file, don't use an openssl engine
	KEY=$PREFIX${KEY:-$DIR/cert.priv}
	KEY_ENGINE=""
fi

# Set the default values for the other parameters
: ${ROOTDEV:=/dev/mapper/vgubuntu-root}
: ${HASHDEV:=/dev/mapper/vgubuntu-hashes}
: ${LINUX_TARGET:=linux}
: ${RECOVERY_TARGET:=recovery}
: ${SIP:=0}
: ${PCRS:=0,2,5,7}
: ${BOOTMODE_PCR:=14}
: ${LINUX_COMMANDLINE:=""}
: ${RECOVERY_COMMANDLINE:=${LINUX_COMMANDLINE}}


die() { echo "$@" >&2 ; exit 1 ; }
warn() { echo "$@" >&2 ; }
debug() { [ "$VERBOSE" == 1 ] && echo "$@" >&2 ; }

cleanup() {
	if [ "$TMP_MOUNT" == "y" ]; then
		warn "$TMP: Unmounting"
		umount "$TMP" || die "DANGER: umount $TMP failed. Secrets might be exposed."
	fi
	rm -rf "$TMP"
}

TMP=`mktemp -d`
TMP_MOUNT=n
trap cleanup EXIT

hex2bin() { perl -ne 'chomp; print pack("H*", $_)' ; }
sha256() { sha256sum - | cut -d' ' -f1 ; }
PCR_DEFAULT=0000000000000000000000000000000000000000000000000000000000000000

#
# Compute the extended value of a PCR register
#
tpm2_trial_extend() {
	initial="$1"
	if [ "0" == "$initial" ]; then
		initial="$PCR_DEFAULT"
	fi
		
	( echo -n "$initial" ; sha256 ) | hex2bin | sha256
}


usage="Safe Boot subcommands:
----
"
commands="commands"

commands() {
	echo "$usage"
	exit 0
}

show_help() {
	if [ "$1" == "-h" -o "$1" == "--help" ]; then
		echo "$2"
		exit 0
	fi
}

key_init_usage="
## safeboot key-init subject

  Generate a new x509 signing key with openssl.
  The subject must be written as:
       /CN=host.example.com/OU=test/O=example.com/

"
usage+=$key_init_usage

key-init() {
	show_help "$1" "$key_init_usage"
	if [ $# == 0 ]; then
		die "$key_init_usage"
	fi

	subject=$1

	if [ "$KEY" == "pkcs11:" ]; then
		die "\$KEY=pkcs11:, use safeboot yubikey-init"
	fi
	if [ -r "$KEY" ]; then
		read -p "WARNING: This will erase the existing key $KEY. Are you sure? " really_do_it
		if [ "$really_do_it" != "y" ]; then
			die "Not overwriting existing key"
		fi

		warn "$KEY: backing up to $KEY.orig"
	fi

	mkdir -p "`dirname $KEY`" "`dirname $CERT`"

	if [ -r "$KEY" ]; then
		mv "$KEY" "$KEY.orig" \
		|| die "$KEY: unable to backup"
	fi
	if [ -r "$CERT" ]; then
		mv "$CERT" "$CERT.orig" \
		|| die "$CERT: unable to backup"
	fi

	openssl \
		req \
		-new \
		-x509 \
		-newkey rsa:2048 \
		-subj "$subject" \
		-keyout "$KEY" \
		-outform PEM \
		-out "$CERT" \
		-days 3650 \
		-sha256 \
	|| die "$KEY: unable to create"
}


yubikey_init_usage="
## safeboot yubikey-init subject

  Generate a new x509 signing key on an attached Yubikey device
  and set the certificate subject to the provided argument.

  The subject must be written as:
       /CN=host.example.com/OU=test/O=example.com/

"
usage+=$yubikey_init_usage
commands+="|yubikey-init"

yubikey-init() {
	show_help "$1" "$yubikey_init_usage"
	if [ $# == 0 ]; then
		die "$yubikey_init_usage"
	fi

	subject=$1

	if [ "$KEY" != "pkcs11:" ]; then
		die "\$KEY != pkcs11: use key-init"
	fi

	if [ -r "$CERT" ]; then
		warn "WARNING! $CERT already exists; copying to $CERT.orig"
		mv "$CERT" "$CERT.orig" \
		|| die "$CERT: unable to make backup"
	fi

	read -p "WARNING: This will erase any existing key on the yubikey. Are you sure? " really_do_it
	if [ "$really_do_it" != "y" ]; then
		die "Not overwriting existing key"
	fi

	# will take a while and overwrite any existing private keys
	warn "Generating new key..."
	yubico-piv-tool \
		-s 9c \
		-a generate \
		-o "$TMP/pubkey.pem" \
	|| die "unable to generate new key"

	warn "Self-signing certificate"
	yubico-piv-tool \
		-s 9c \
		-a verify-pin \
		-a selfsign-certificate \
		-S "$subject" \
		-i "$TMP/pubkey.pem" \
		-o "$CERT" \
	|| die "Unable to self-sign certificate"

	warn "Importing self-signed certificate into key"
	yubico-piv-tool \
		-s 9c \
		-a import-certificate \
		-i "$CERT" \
	|| die "Unable to import certificate into key"

	yubico-piv-tool \
		-a status \
	|| die "Unable to retrieve key status"
}


uefi_sign_keys_usage="
## safeboot uefi-sign-keys

  Create three signed certificates for the PK, KEK, and db using
  the attached Yubikey and store them in the UEFI SecureBoot configuration.
  You will have to authenticate to the yubikey multiple times during this process.
"
usage+=$uefi_sign_keys_usage
commands+="|uefi-sign-keys"

uefi-sign-keys() {
	show_help "$1" "$uefi_sign_keys_usage"

	cert-to-efi-sig-list \
		-g `uuidgen` \
		"$CERT" \
		"$TMP/cert.esl" \
	|| die "cert-to-efi-sig-list failed"

	## Cache the yubico pin since it will be used multiple times
	#read -s -p 'Yubikey login PIN: ' pin
	#echo

	# Use the sign-efi-sig-list from our build so that the
	# -e option exists
	for key in db KEK PK; do
		warn "Signing UEFI variable $key"
		sign-efi-sig-list.safeboot \
			$KEY_ENGINE \
			-k "$KEY" \
			-c "$CERT" \
			$key \
			$TMP/cert.esl \
			$PREFIX$DIR/$key.auth \
		|| die "$key: Signing failed"
	done

	uefi-set-keys
}

uefi_set_keys_usage="
## safeboot uefi-set-keys

  Store the PK, KEK, and db into the UEFI Secure Boot configuration
  variables.  This must be done once during system setup.

"
usage+=$uefi_set_keys_usage
commands+="|uefi-set-keys"

uefi-set-keys()
{
	show_help "$1" $uefi_set_keys_usage

	# The order of update must be from lowest to highest
	for key in db KEK PK; do
		if [ ! -r "$PREFIX$DIR/$key.auth" ]; then
			die "$PREFIX$DIR/$key.auth not found: run safeboot uefi-sign-keys"
		fi

		warn "Installing UEFI variable $key"

		efi-updatevar -f "$PREFIX$DIR/$key.auth" "$key" \
		|| die "$key: updating key failed; is the BIOS in setup mode?"
	done
}


luks_seal_usage="
## safeboot luks-seal [0,2,5,7... 14]

  Generate a new LUKS encryption key for the block devices in /etc/crypttab,
  sealed with the optional comma separated list of TPM PCRs.  PCR 14 will be
  used to indicate a 'postboot' status to prevent the key from being unsealed
  after the initramfs has run.

  If this is the first time the disk has been sealed, /etc/crypttab will be updated
  to include a call to this script to retrieve the keys from the TPM.
  Right now only a single crypt disk is supported.
"
usage+=$luks_seal_usage
commands+="|luks-seal"

luks-seal() {
	show_help "$1" "$luks_seal_usage"

	if [ ! -z "$1" ]; then
		PCRS=$1
		shift
	fi
	if [ ! -z "$1" ]; then
		BOOTMODE_PCR=$1
		shift
	fi
	
	KEYSLOT=1
	HANDLE=0x81000000

	# check to see if the initramfs hook is installed
	if [ ! -x "$PREFIX/etc/initramfs-tools/hooks/tpm-unseal" ]; then
		warn "!!! $PREFIX/etc/initramfs-tools/hooks/tpm-unseal is not installed; this will probably not work"
	fi

	# and make sure that the unlock script is installed as expected
	if [ ! -x "$PREFIX/usr/sbin/safeboot" ]; then
		warn "!!! $PREFIX/usr/sbin/safeboot is not installed; this will probably not work"
	fi

	if [ `wc -l < "$PREFIX/etc/crypttab"` -ne 1 ]; then
		die "!!! $PREFIX/etc/crypttab must have only one entry"
	fi

	# Determine which device is the cryptdisk
	uuid=`perl -ne '/UUID=(.*?) / && print "$1"' $PREFIX/etc/crypttab`
	if [ -z "$uuid" ]; then
		die "Unable to find UUID in crypttab"
	fi
	dev=`blkid -U $uuid`
	if [ -z "$dev" ]; then
		die "Unable to find device for uuid $uuid"
	fi

	# if the TPM2 resource manager is running, talk to it.
	# otherwise use a direct connection to the TPM.
	if ! pidof tpm2-abrmd > /dev/null ; then
		export TPM2TSSENGINE_TCTI="device:/dev/tpmrm0"
	fi

	# Use a tmpfs mount instead of just a temp directory so that
	# the disk encryption key doesn't touch a persistent disk.
	mount -t tmpfs none "$TMP" \
	|| die "Unable to mount temp directory"

	chmod 700 "$TMP"
	TMP_MOUNT=y

	dd \
		if=/dev/urandom \
		of="$TMP/key.bin" \
		bs=32 \
		count=1 \
	|| die "Unable to generate random key"

	# If pre-computed PCRs are known, they can be used here instead
	tpm2_pcrread -o "$TMP/pcrs.bin" "sha256:$PCRS" \
		>> /tmp/tpm.log \
	|| die "Unable to read TPM PCRs"

	# Add a "normal" entry for PCR 14, which ensures that the TPM
	# will only unseal during a normal boot, not a recovery boot.
	# the unseal script will also extend PCR14 after unsealing
	# to prevent the TPM from unsealing the secret a second time
	pcr14=`echo -n "${LINUX_TARGET}" | tpm2_trial_extend $PCR_DEFAULT`
	warn "PCR$BOOTMODE_PCR=$pcr14"
	echo -n "$pcr14" | hex2bin \
		>> "$TMP/pcrs.bin"
	xxd -g1 "$TMP/pcrs.bin"

	tpm2_createpolicy \
		--policy-pcr \
		--pcr-list "sha256:$PCRS,$BOOTMODE_PCR" \
		--pcr "$TMP/pcrs.bin" \
		--policy "$TMP/policy.digest" \
		>> /tmp/tpm.log \
	|| die "Unable to create TPM policy"

	tpm2_createprimary \
		--key-context "$TMP/primary.context" \
		>> /tmp/tpm.log \
	|| die "Unable to create TPM primary object"

	# Start a secret session with the TPM
	#tpm2_startauthsession \
	#	--session "$TMP/session.context" \
	#|| die "Unable to start TPM session"
	#
	#tpm2_policysecret \
	#	--session "$TMP/session.context" \
	#	--object-context "$TMP/primary.context" \
	#|| die "Unable to set secret policy"
	#	--parent-auth "$TMP/session.context" \
	#	--key-auth $HANDLE \

	warn "Sealing secret with TPM"
	tpm2_create \
		--parent-context "$TMP/primary.context" \
		--policy "$TMP/policy.digest" \
		--sealing-input "$TMP/key.bin" \
		--public "$TMP/public.bin" \
		--private "$TMP/private.bin" \
		>> /tmp/tpm.log \
	|| die "Unable to create TPM key context"

	tpm2_load \
		--parent-context "$TMP/primary.context" \
		--public "$TMP/public.bin" \
		--private "$TMP/private.bin" \
		--key-context "$TMP/key.context" \
		>> /tmp/tpm.log \
	|| die "Unable to load TPM with key"
		
	warn "Installing sealed secret into TPM"
	tpm2_evictcontrol \
		--object-context "$HANDLE" \
		>> /tmp/tpm.log \
	|| die "Unable to remove old TPM key context $HANDLE"

	tpm2_evictcontrol \
		--object-context "$TMP/key.context" \
		>> /tmp/tpm.log \
	|| die "Unable to load TPM key context into TPM"

	# Verify that the key actually works -- this might break
	# if there are different PCRs
#	warn "Verifying sealed secret"
#	if tpm2_unseal \
#		--object-context $HANDLE \
#		--auth pcr:"$PCRS,$BOOTMODE_PCR" \
#		--output "$TMP/key2.bin" \
#		>> /tmp/tpm.log \
#	; then
#		cmp "$TMP/key.bin" "$TMP/key2.bin" \
#		|| die "Keys do not match; something failed"
#	else
#		warn "Unable to unseal (probably due to PCR$BOOTMODE_PCR); ignored"
#	fi

	# make sure the crypttab has the unlock script referenced
	if ! grep keyscript "$PREFIX/etc/crypttab" > /dev/null ; then
		warn "adding crypttab unseal script"
		sed -i.orig 's:,discard$:,discard,keyscript=/usr/sbin/safeboot-tpm-unseal:' $PREFIX/etc/crypttab \
		|| die "$PREFIX/etc/crypttab: unable to add keyscript"

		warn "***** You should update your ramdisk and resign the kernel:"
		warn "   sudo update-initramfs -u"
	fi


	# ask for the disk encryption key
	for tries in 1 2 3 fail; do
		read -s -p "$dev: Current recovery password: " recovery_key
		echo
		echo -n "$recovery_key" > "$TMP/recovery.key"

		warn "Removing old LUKS TPM key (if it exists)"
		cryptsetup luksKillSlot \
			--key-file "$TMP/recovery.key" \
			"$dev" $KEYSLOT \
		|| warn "$dev: Unable to remove old key slot (ignored)"

		warn "Adding new LUKS TPM key"
		cryptsetup luksAddKey \
			--key-file "$TMP/recovery.key" \
			--key-slot $KEYSLOT \
			"$dev" "$TMP/key.bin" \
		&& break

		warn "$dev: Unable to add key slot"

		if [ $tries == fail ]; then
			die "$dev: Unable to add key"
		fi
	done

	warn "$dev: sealed with PCR $PCRS,$BOOTMODE_PCR"
}

sign_kernel_usage="
## safeboot sign-kernel 'boot-name' parameters...

  Create an EFI boot menu entry for 'boot-name', with the specified
  kernel, initrd and command line bundled into an executable and signed.
  This is the raw command; you might want to use hash-and-sign or
  recovery-sign instead.

"
usage+=$sign_kernel_usage
commands+="|sign-kernel"

sign-kernel() {
	show_help "$1" "$sign_kernel_usage"

	TARGET="$1" ; shift

	if [ -z "$TARGET" ]; then
		die $sign_kernel_usage
	fi

	OUTDIR="${EFIDIR}/${TARGET}"

#	if [ ! -r "$CERT" ]; then
#		warn "Extracting signing cert from yubikey"
#		yubico-piv-tool \
#			-s 9c \
#			-a read-certificate \
#			-o "$CERT" \
#		|| die "$CERT: unable to read from yubikey"
#	fi

	if [ ! -d "$OUTDIR" ]; then
		warn "$OUTDIR: Creating directory on EFI System Partition"
		mkdir -p "$OUTDIR" \
		|| die "$OUTDIR: unable to create"
	fi

	if ! efibootmgr | grep "^Boot.* $TARGET\$" ; then
		# determine the device the EFI system partition is on
		DEV="`df "$OUTDIR" | tail -1 | cut -d' ' -f1`"

		warn "$OUTDIR: Creating boot menu item on $DEV"
		efibootmgr \
			--quiet \
			--create \
			--disk "$DEV" \
			--part 1 \
			--label "$TARGET" \
			--loader "\\EFI\\$TARGET\\linux.efi" \
		|| die "efibootmgr: failed to create $TARGET entry"
	fi

	if [ $# == 0 ]; then
		warn "Using /proc/cmdline"
		cat /proc/cmldine > "$TMP/cmdline.txt"
	else
		echo -n "$@" > "$TMP/cmdline.txt"
	fi

	warn "$TMP/linux.efi: Creating merged Linux/initrd image"
	objcopy \
		--add-section .osrel="$PREFIX/etc/os-release" \
		--add-section .cmdline="$TMP/cmdline.txt" \
		--add-section .linux="$KERNEL" \
		--add-section .initrd="$INITRD" \
		--change-section-vma .osrel=0x20000 \
		--change-section-vma .cmdline=0x30000 \
		--change-section-vma .linux=0x40000 \
		--change-section-vma .initrd=0x3000000 \
		"$PREFIX/usr/lib/systemd/boot/efi/linuxx64.efi.stub" \
		"$TMP/linux.efi" \
	|| die "linux.efi: unable to create"

	warn "$OUTDIR/linux.efi: Signing (ignore warnings about gaps)"
	sbsign.safeboot \
		$KEY_ENGINE \
		--key "$KEY" \
		--cert "$CERT" \
		--output "$OUTDIR/linux.efi.new" \
		"$TMP/linux.efi" \
	|| die "$OUTDIR/linux.efi: Unable to sign"

	# Duplicate the old image and atomically move the new kernel
	# image to avoid potentially leaving an unbootable system
	if [ -r "$OUTDIR/linux.efi" ]; then
		cp "$OUTDIR/linux.efi" "$OUTDIR/linux.efi.old" \
		|| die "$OUTDIR/linux.efi.old: unable to backup old image"
	fi

	mv "$OUTDIR/linux.efi.new" "$OUTDIR/linux.efi" \
	|| die "$OUTDIR/linux.efi: unable to install new image"

	echo "Kernel commandline: '`cat $TMP/cmdline.txt`'"
	sha256sum "$OUTDIR/linux.efi"

	if [ -r "$TMP/verity.log" ]; then
		# stash a copy of the verity log in the boot directory
		# so that repeat signing can be done more quickly
		cp "$TMP/verity.log" "$OUTDIR"
	fi
}

linux_sign_usage="
## safeboot linux-sign [target [parameters...]]

  Generate dm-verity hashes and then sign the Linux with the root hash added
  to the kernel command line.

  If HASH is set in the environment, it will be used instead of recomputing
  the dmverity hashes (which can take some time).
  
"
usage+=$linux_sign_usage
commands+="|linux-sign"

linux-sign()
{
	show_help "$1" "$linux_sign_usage"

	# default is linux
	TARGET=${1:-${LINUX_TARGET}}

	if [ "$SIP" == 1 ]; then
		if mount | grep "${ROOTDEV}" ; then \
			warn "$ROOTDEV: unmounting and checking"
			mount -o ro,noatime,remount "${ROOTDEV}" ; \
			fsck.ext4 -f "${ROOTDEV}"
		fi

		if [ ! -z "$HASH" ]; then
			warn "$ROOTDEV: Using hash $HASH"
		elif [ ! -z "$HASHFILE" ]; then
			warn "$ROOTDEV: Using hash file $HASFILE"
			HASH="`awk '/Root hash:/ { print $3 }' $HASHFILE`"
		else
			echo "$ROOTDEV: Computing hashes: this will take a while..."
			veritysetup format \
				--debug \
				"${ROOTDEV}" \
				"${HASHDEV}" \
				| tee $TMP/verity.log \
			|| die "$ROOTDEV: unable to compute hashes"

			HASH="`awk '/Root hash:/ { print $3 }' $TMP/verity.log`"
		fi

		if [ -z "$HASH" ]; then
			die "$ROOTDEV: root hash not in log?"
		fi

		ROOT_ARGS="\
			root=/dev/mapper/vroot \
			fsck.mode=skip \
			verity.hashdev=${HASHDEV} \
			verity.rootdev=${ROOTDEV} \
			verity.hash=$HASH \
		"
	else
		warn "SIP mode is not enabled"
		ROOT_ARGS="\
			root=${ROOTDEV}
		"
	fi

	sign-kernel "$TARGET" \
		$LINUX_COMMANDLINE \
		$ROOT_ARGS \
		tpm.pcrs=$PCRS \
		tpm.mode=$TARGET \
		"$@" \
	|| die "Kernel signing failed!"
}

recovery_sign_usage="
## safeboot recovery-sign [kernel command line...]

  Sign the Linux kernel and initrd into the recovery target.

  If HASH is set in the environment, it will be used instead of recomputing
  the dmverity hashes (which can take some time).
  
"
usage+=$recovery_sign_usage
commands+="|recovery-sign"

recovery-sign()
{
	show_help "$1" "$recovery_sign_usage"

	# default is recovery
	TARGET=${1:-${RECOVERY_TARGET}}

	sign-kernel "$TARGET" \
		$LINUX_COMMANDLINE \
		root=${ROOTDEV} \
		blockdev.ro=${ROOTDEV} \
		tpm.mode=${TARGET} \
		"$@" \
	|| die "Kernel signing failed!"
}

recovery_usage="
## safeboot recovery [reboot]

  Configure the next boot for a recovery.  If reboot is passed in,
  the system will be rebooted now.
  
"
usage+=$recovery_usage
commands+="|recovery"

recovery()
{
	show_help "$1" "$recovery_usage"
	# Find the recovery entry in the efibootmgr
	entry=`efibootmgr | perl -ne '/^Boot([0-9A-F]+). recovery$/ and print $1'`
	if [ -z "$entry" ]; then
		die "recovery boot entry not in efibootmgr?"
	fi

	warn "recovery: boot mode $entry"
	efibootmgr --bootnext "$entry" \
		|| die "Boot$entry: unable to set bootnext"

	if [ "$1" == "reboot" ]; then
		warn "Initiating reboot!"
		reboot
	fi
}


if [ $# -lt 1 ]; then
	die "Usage: $0 [$commands] ...." 
fi

command=$1 ; shift
#echo "$commands"

case "$command" in
	-h|--help)
		echo "$usage"
		exit 0
		;;
	#$commands)
	yubikey-init|key-init|uefi-sign-keys|uefi-set-keys|luks-seal|sign-kernel|linux-sign|recovery-sign|recovery|tpm2_trial_extend)
		$command "$@"
		;;
	*)
		die "$0: subcommand $command unknown"
		;;
esac
