#!/bin/bash

PROG=${0##*/}

if [[ $0 = /* ]]; then
        BASEDIR=${0%/*}
elif [[ $0 = */* ]]; then
        BASEDIR=$PWD/${0%/*}
else
        BASEDIR=$PWD
fi

set -euo pipefail -o noclobber
shopt -s extglob

function usage {
	((${1:-1} > 0)) && exec 1>&2
	cat <<EOF
Usage: $PROG [options] [-o FILE] [-A | -D] POLICY

  The first form computes the policyDigest of the given {POLICY}.

  A {POLICY} starts with an optional TPM 2.0 command-code (e.g., TPM2_CC_Sign),
  and the rest is a sequence of {tpm2 policy*} command-lines separated by ';':

       $PROG ... tpm2 policy... args... \\; tpm2 policy args...

  but without any {--session}|{-S} nor {--policy}|{-L} options.

  For alternations use {tpm2 policyor} with each alternative given as a sub-
  {POLICY} surrounded with '(' and ')':

       $PROG ... tpm2 policyor '(' tpm2 policy... ';' ... ')' '(' ... ') ...

  If -A is given then {tpm2 policycommandcode} will be added at the end for
  enabling TPM2_ActivateCredential().

  If -D is given then {tpm2 policycommandcode} will be added at the end for
  enabling TPM2_RSA_Decrypt().

  Options:

   -h	    This message.
   -v	    Verbose.
   -x	    Trace.

   -f	    Force (overwrite FILE).
   -o FILE  Where to put the SHA-256 policyDigest (hex-encoded).
   -A	    Add {tpm2 policycommandcode TPM2_CC_ActivateCredential}.
   -D	    Add {tpm2 policycommandcode TPM2_CC_RSA_Decrypt}.

  E.g.:

      $ # Require that PCR 11 be unextended
      $ $PROG tpm2 policypcr -l "sha256:11"

      $ # Allow signing and credential activation only
      $ $PROG tpm2 policyor '(' tpm2 policycommandcode TPM2_CC_Sign ')' \\
				  '(' tpm2 policycommandcode TPM2_CC_ActivateCredential ')'
EOF
	exit "${1:-1}"
}

(($# == 0)) && usage 0

# shellcheck disable=SC1090
. "$BASEDIR/../functions.sh"

out=
force=false
activate=false
rsa_decrypt=false
session_context=
command_code=
VERBOSE=0
while getopts +:ADhefo:vx opt; do
case "$opt" in
A)	activate=true;;
D)	rsa_decrypt=true;;
h)	usage 0;;
f)	force=true;;
o)	out=$OPTARG;;
v)	((++VERBOSE));;
x)	set -vx;;
*)	usage;;
esac
done
shift $((OPTIND - 1))

! $activate  || ! $rsa_decrypt || die "-A and -D are mutually exclusive"
$activate    && command_code=TPM2_CC_ActivateCredential
$rsa_decrypt && command_code=TPM2_CC_RSA_Decrypt

# Make a temp dir and remove it when we exit:
d=
trap 'rm -rf "$d"' EXIT
d=$(mktemp -d)

policyDigest=$(make_policyDigest "${d}/session" "${d}/policy" $command_code "$@")
[[ -z $out ]] || ! $force >| "$out"
[[ -z $out ]] ||   $force > "$out"
echo "$policyDigest"
