Document: safeboot
Title: Debian safeboot Manual
Author: <insert document author here>
Abstract: This manual describes what safeboot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/safeboot/safeboot.sgml.gz

Format: postscript
Files: /usr/share/doc/safeboot/safeboot.ps.gz

Format: text
Files: /usr/share/doc/safeboot/safeboot.text.gz

Format: HTML
Index: /usr/share/doc/safeboot/html/index.html
Files: /usr/share/doc/safeboot/html/*.html
